# This workflow is triggered on PR being opened, synced, reopened, closed.
# It dispatches workflow on CompFuzzCI repository, where fuzzing of the PR is handled.

name: Fuzzing on PR (excluding forks)
on:
  pull_request:
    branches:
      - master
  
jobs:
  FuzzOnPR:
    if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.repo.owner.login == 'dafny-lang'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CompFuzzCI
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZCI_PAT }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'CompFuzzCI',
                  repo: 'DafnyCompilerFuzzer',
                  workflow_id: 'fuzz.yaml',
                  ref: 'main',
                  inputs: {
                      commit: '${{ github.event.pull_request.head.sha }}',
                      main_commit: '${{github.event.pull_request.base.sha}}',
                      branch: '${{github.event.pull_request.head.ref}}',
                      duration: '3600',
                      instance: '2'
                  }
              })